[package]
name = "tinyhttpd"
version = "0.2.0"
authors = ["Satoshi Moriai <satoshi.moriai@gmail.com>"]
edition = "2018"

[dependencies]
tiny_http = "0.12"
ascii = "1.0"
log = "0.4"
simplelog = "0.12"
time = "0.3"
